SELECT
	dsc.BUSINESS_NAME,
	ROUND(SUM(dss.SALES_VALUE),2) AS TOTAL_SALES
FROM data_store_sales dss
INNER JOIN data_store_cad dsc ON (dss.STORE_CODE = dsc.STORE_CODE )
WHERE dss.`DATE` BETWEEN '2019-01-01' AND '2019-03-31'
GROUP BY dsc.BUSINESS_NAME
ORDER BY TOTAL_SALES DESC