SQL_TOP_10_EXPENSIVE_PRODUCTS = """
SELECT
    PRODUCT_COD,
    PRODUCT_NAME,
    PRODUCT_VAL,
    DEP_NAME,
    SECTION_NAME
FROM data_product
ORDER BY PRODUCT_VAL DESC
LIMIT 10;
"""


SQL_BEVERAGES_AND_BAKERY_SECTIONS = """
SELECT DISTINCT
    DEP_NAME,
    SECTION_COD,
    SECTION_NAME
FROM data_product
WHERE DEP_NAME IN ('BEBIDAS', 'PADARIA')
ORDER BY DEP_NAME, SECTION_NAME;
"""


SQL_Q1_2019_SALES_BY_BUSINESS_AREA = """
SELECT
    sc.BUSINESS_NAME,
    sc.BUSINESS_CODE,
    SUM(ss.SALES_VALUE) AS TOTAL_SALES_VALUE
FROM data_store_sales ss
JOIN data_store_cad sc
    ON sc.STORE_CODE = ss.STORE_CODE
WHERE ss.DATE BETWEEN '2019-01-01' AND '2019-03-31'
GROUP BY
    sc.BUSINESS_NAME,
    sc.BUSINESS_CODE
ORDER BY TOTAL_SALES_VALUE DESC;
"""


QUERY_STORE_CAD = """
SELECT
    STORE_CODE,
    STORE_NAME,
    START_DATE,
    END_DATE,
    BUSINESS_NAME,
    BUSINESS_CODE
FROM data_store_cad
"""


QUERY_STORE_SALES = """
SELECT
    STORE_CODE,
    DATE,
    SALES_VALUE,
    SALES_QTY
FROM data_store_sales
WHERE DATE BETWEEN '2019-01-01' AND '2019-12-31'
"""


QUERY_IMDB_MOVIES = """
SELECT
    Genre,
    Rating,
    Votes,
    RevenueMillions,
    Metascore
FROM IMDB_movies
WHERE Genre IS NOT NULL
  AND Rating IS NOT NULL;
"""
